name: Build Docker image

on:
  push:
    branches: [ ecnc ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to ghcr.io
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract Docker meta from GitHub events
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/${{ github.repository_owner }}/kratos

    - name: Build and push Docker images
      uses: docker/build-push-action@v2.9.0
      with:
        # Build's context is the set of files located in the specified PATH or URL
        context: .
        # Path to the Dockerfile
        file: .docker/Dockerfile-build
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}